In [ ]:
numpy=>numerical python,

In [ ]:
list,tuple 
image=>

In [3]:
import numpy as np

In [ ]:
from numpy import *

In [2]:
li=[1,2,3,4]
type(li)

list

In [ ]:
dir(np)

In [6]:
#Array can be created from a list
import numpy as np
a = np.array([1, 4, 5, 8],float)

In [6]:
a

array([1, 4, 5, 8])

In [7]:
a.shape

(4,)

In [10]:
a.dtype

dtype('float64')

In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
help(np.array)

In [12]:
#multidimensional array
a=np.array(([1, 2, 3], [4, 5, 6]), float)


In [13]:
print(a)
print(type(a))

[[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'>


In [14]:
a.shape

(2, 3)

In [7]:
a=np.array([[1,2,3],[2,5,6],[7,8,9]])
a.shape

(3, 3)

In [16]:
a

array([[1, 2, 3],
       [2, 5, 6],
       [7, 8, 9]])

In [17]:
a.dtype

dtype('int32')

In [18]:
len(a)

3

In [11]:
a=np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(a)

[[1 2 3]
 [2 5 6]
 [7 8 9]]


In [21]:
len(a)

10

In [22]:
a.shape

(10,)

In [41]:
a=a.reshape(5,2)

In [42]:
print(a)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
a.shape

(5, 2)

In [ ]:
len(a)

In [31]:
a.copy()

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
a=np.array([2,4,6,8,10])

In [13]:
b=a.copy()

In [14]:
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [35]:
print(type(a))

<class 'numpy.ndarray'>


In [36]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [ ]:
dir(np)

In [37]:
a=a.tolist()

In [38]:
print(a)
print(type(a))

[2, 4, 6, 8, 10]
<class 'list'>


In [1]:
a=a.flatten()

NameError: name 'a' is not defined

In [47]:
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [48]:
a=a.tostring()
print(a)
print(type(a))

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00'
<class 'bytes'>


C:\Users\Technologics\AppData\Local\Temp\ipykernel_13840\3673439716.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  a=a.tostring()


In [49]:
a=np.array(([1,2],[3,4]))

In [51]:
print(a)

[[1 2]
 [3 4]]


In [50]:
a.transpose()

array([[1, 3],
       [2, 4]])

In [52]:
a=np.array([1,2,3])

In [53]:
a.fill(0)

In [54]:
print(a)

[0 0 0]


In [4]:
np.arange(5,dtype=float)

array([0., 1., 2., 3., 4.])

In [55]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [58]:
import numpy as np
print(np.__version__)

1.23.5


In [ ]:
Write a NumPy program to get help on the add function.

In [ ]:
 Write a NumPy program to create a 3x3 identity matrix

In [ ]:
Write a NumPy program to generate a random number between 0 and 1

In [ ]:
converting multidimensional array to 1D array
concatenating two arrays w.r.t axis

In [ ]:
how to increase the dimension of an array

In [6]:
a=np.array([1,2,3])

In [ ]:
print(a)

In [7]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [8]:
a[:np.ne]

AttributeError: module 'numpy' has no attribute 'ne'

In [ ]:
Write a NumPy program to test whether any of the elements of a given array is
non-zero.



In [ ]:
Write a NumPy program to test whether none of the elements of a given array
is zero.


In [ ]:
pandas=>used for analysing data

In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv("Heart_Disease_Prediction.csv")

In [ ]:
data.head(10)

In [ ]:
data.tail()

In [ ]:
data.info()

In [ ]:
data["Age"].isnull

In [ ]:
data["Age"].unique

In [ ]:
dir(data)